clone:
    depth: 1

pipelines:
    branches:
        master:
            - parallel:
                  - step:
                        name: Deploy Typescript Docker image (12)
                        services:
                            - docker
                        script:
                            - export IMG_NAME=usertechnologies/base-img-node:12
                            - docker build --build-arg NODE_VERSION=12 -t $IMG_NAME -f Dockerfile.typescript .
                            - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
                            - docker push $IMG_NAME
                  - step:
                        name: Deploy Typescript Docker image (14)
                        services:
                            - docker
                        script:
                            - export IMG_NAME=usertechnologies/base-img-node:14
                            - docker build --build-arg NODE_VERSION=12 -t $IMG_NAME -f Dockerfile.typescript .
                            - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
                            - docker push $IMG_NAME
                  - step:
                        name: Deploy Typescript Docker image (16)
                        services:
                            - docker
                        script:
                            - export IMG_NAME=usertechnologies/base-img-node:16
                            - docker build --build-arg NODE_VERSION=16 -t $IMG_NAME -f Dockerfile.typescript .
                            - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
                            - docker push $IMG_NAME
