ARG NODE_VERSION=16

FROM amazon/aws-lambda-nodejs:$NODE_VERSION

# -----------------------------------------------------------------------------
# Install general utilities
RUN yum update -y
RUN yum install -y wget bsdtar which git openssh zip unzip jq curl

RUN yum install -y amazon-linux-extras

# -----------------------------------------------------------------------------
# Install Java and JDK

RUN amazon-linux-extras install java-openjdk11

RUN java --version

# -----------------------------------------------------------------------------
# Install dependency-check

RUN wget -qO- https://github.com/jeremylong/DependencyCheck/releases/download/v7.3.2/dependency-check-7.3.2-release.zip | bsdtar -xf- -C /opt

# Copy NVD database definitions. Faster than downloading from internet.
COPY --from=owasp/dependency-check-action /usr/share/dependency-check/data /opt/dependency-check/data

RUN chmod u+x /opt/dependency-check/bin/dependency-check.sh
RUN ln -s /opt/dependency-check/bin/dependency-check.sh /usr/bin/dependency-check

# This forces NVD database to initialize, resulting in faster runs.
RUN dependency-check --scan .
RUN dependency-check --version

# -----------------------------------------------------------------------------
# Install sonar-scanner

RUN wget -qO- https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747.zip | bsdtar -xf- -C /opt

RUN chmod u+x /opt/sonar-scanner-4.7.0.2747/bin/sonar-scanner
RUN ln -s /opt/sonar-scanner-4.7.0.2747/bin/sonar-scanner /usr/bin/sonar-scanner

RUN sonar-scanner --version

# -----------------------------------------------------------------------------
# Install aws-cli

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip -q awscliv2.zip
RUN ./aws/install

RUN aws --version

# -----------------------------------------------------------------------------
# Install docker

RUN amazon-linux-extras install docker
RUN docker --version

# -----------------------------------------------------------------------------
# Install NodeJS

RUN node --version
RUN npm --version

RUN npm i -g yarn
RUN yarn --version

# Set alias for releasing
RUN echo -e '#!/bin/sh\nnpx --package @sladg/nextjs-lambda@3.20.4 next-utils shipit --changelog --gitUser Bender --gitEmail admin+bitbucket-pipelines@usertechnologies.com' >/usr/bin/release
RUN chmod +x /usr/bin/release
